Function for testing directory is writable
messerli-informatik-ag/file-system pull request #22
Opened 2020-06-18 12:17 UTC by robie2011

2020-06-18 15:28 UTC, janhohenheim requested changes

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem.Test/FileSystemTest.cs
> +            if (Environment.OSVersion.Platform == PlatformID.Unix ||
Use a [reusable custom fact attribute](https://stackoverflow.com/a/4421941/5903309) for this

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem.Test/FileSystemTest.cs
> +        public void CheckDirectoryIsWritable()
Mention the fact that this only runs on Windows

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem.Test/FileSystemTest.cs
> +            Assert.False(isWritable);
You are testing two things here. Split this test.

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem/FileSystem.cs
> +        public bool DirectoryIsWritable(string path)
Follow the conventions of other predicates and start the method with "Is": `IsDirectoryWritable`

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem/FileSystem.cs
> +                return false;
This will return false even if only the deletion fails.

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem/IFileSystem.cs
> +        /// Returns boolean that represents directory is writeable.
This piece of documentation simply restates the method name and as such can be omitted.

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem/IFileSystem.cs
> +        /// <returns>A boolean that represents directory is writeable.</returns>
Remove this line as well

2020-06-18 15:28 UTC, janhohenheim commented on FileSystem/IFileSystem.cs
> +        /// <param name="path">The relative or absolute path to the directory to search. This string is not case-sensitive.</param>
"not case-sensitive" -> "case-insensitive"

2020-06-19 07:44 UTC, robie2011 commented on FileSystem.Test/FileSystemTest.cs
> +            Assert.False(isWritable);
This is one test. The first part - including first assert - is preparation for actual testing.

2020-06-19 07:44 UTC, robie2011 commented on FileSystem/IFileSystem.cs
> +        /// Returns boolean that represents directory is writeable.
Ok 9a84d40937ee86dfc454b13b69ac580354a23839

2020-06-19 07:44 UTC, robie2011 commented on FileSystem/IFileSystem.cs
> +        /// <param name="path">The relative or absolute path to the directory to search. This string is not case-sensitive.</param>
I have copied that from GetFiles method. Are you sure? What about unix/linux systems?

2020-06-19 07:44 UTC, robie2011 commented on FileSystem/FileSystem.cs
> +                return false;
Yes, that was intentionally. 
I think in our context we want to write AND delete files in directory.
Isn't that necessary?

2020-06-19 07:44 UTC, robie2011 commented on FileSystem/FileSystem.cs
> +        public bool DirectoryIsWritable(string path)
https://github.com/messerli-informatik-ag/file-system/pull/22/commits/cd7be418ffe2f73ac6cfdd9aa1b751314b673f9c

2020-06-19 07:44 UTC, robie2011 commented on FileSystem.Test/FileSystemTest.cs
> +        public void CheckDirectoryIsWritable()
https://github.com/messerli-informatik-ag/file-system/pull/22/commits/cd7be418ffe2f73ac6cfdd9aa1b751314b673f9c

2020-06-19 07:44 UTC, robie2011 commented on FileSystem.Test/FileSystemTest.cs
> +            if (Environment.OSVersion.Platform == PlatformID.Unix ||
Good idea. I see there is already an Attribute called `SkippableFact` https://stackoverflow.com/a/35871507/2248405.
fb2c658

2020-06-19 07:44 UTC, robie2011 commented on FileSystem/IFileSystem.cs
> +        /// <returns>A boolean that represents directory is writeable.</returns>
9a84d40

2020-06-19 07:44 UTC, robie2011 commented on FileSystem.Test/FileSystemTest.cs
> +            if (Environment.OSVersion.Platform == PlatformID.Unix ||
test

2020-06-19 07:46 UTC, jnferner commented on FileSystem.Test/FileSystemTest.cs
> +            if (Environment.OSVersion.Platform == PlatformID.Unix ||
Good catch, feel free to use that NuGet package

2020-06-19 07:51 UTC, jnferner commented on FileSystem.Test/FileSystemTest.cs
> +            Assert.False(isWritable);
Then rename the test to reflect expected failure

2020-06-19 07:58 UTC, robie2011 commented on FileSystem/IFileSystem.cs
> +        /// <param name="path">The relative or absolute path to the directory to search. This string is not case-sensitive.</param>
5ba99b5

2020-06-19 07:59 UTC, robie2011 commented on FileSystem.Test/FileSystemTest.cs
> +            Assert.False(isWritable);
0757299

2020-06-19 08:09 UTC, janhohenheim approved these changes

2020-06-22 09:22 UTC, merged